### ISSUE TITLE
Why password protect the release?

### ISSUE THREAD

**Issue by Zeokat** [CpuDbg/CpuDbg#17]
Hello, it caught my attention that the executable is password protected, why?

I have seen that sometimes people resort to protecting malicious files with passwords. I don't want to say that this is the case, but it is curious to see the debugger protected by a password.

And what is the purpose of the embedded executable vm.exe?

Thanks in advance.

**Comment by CpuDbg** [comment]
The purpose of setting a password is to prevent certain antivirus software or HIPS (Host Intrusion Prevention Systems) from falsely reporting a virus. (If everyone dislikes the password, I can remove the compression password in the next version.)

vm.exe is the main file of the 7z compression software, and vm.dll is a module of the 7z compression software. Currently, I remember two functions that use 7z.

Extracting the help documentation of Cpudbg (because it is in HTML format).
![image](https://github.com/CpuDbg/CpuDbg/assets/134661959/256dac06-32c4-4275-9499-a0cf7a0848e9)

Saving the hijack module code. In Alt+E, there is a function to save the DLL hijack code. Because there are quite a few files, vm.exe is used. (It also has a password set.)
![PixPin_2024-06-22_11-43-20](https://github.com/CpuDbg/CpuDbg/assets/134661959/5d578093-c7fa-4f1c-acc2-5ddc517ff429)

**Comment by Zeokat** [comment]
Thanks for the clarification, maybe you find time/interest to read and answer some reverser questions about CpuDbg in next topic: https://forum.exetools.com/showthread.php?t=21003

Some people also warned about the presence of suspicios references to video card names/references, as many malicious software contains. With a few clarifications the doubts are resolved.

Thanks you for your effort in advance.

**Comment by CpuDbg** [comment]
> Thanks for the clarification, maybe you find time/interest to read and answer some reverser questions about CpuDbg in next topic: https://forum.exetools.com/showthread.php?t=21003
> 
> Some people also warned about the presence of suspicios references to video card names/references, as many malicious software contains. With a few clarifications the doubts are resolved.
> 
> Thanks you for your effort in advance.

I'm sorry, I don't have an account for that forum, and I can't register because it requires an invitation code  :(

**Comment by Ahmadmansoor** [comment]
> > Thanks for the clarification, maybe you find time/interest to read and answer some reverser questions about CpuDbg in next topic: https://forum.exetools.com/showthread.php?t=21003
> > Some people also warned about the presence of suspicios references to video card names/references, as many malicious software contains. With a few clarifications the doubts are resolved.
> > Thanks you for your effort in advance.
> 
> I'm sorry, I don't have an account for that forum, and I can't register because it requires an invitation code :(

Hi
How can I reach you ( send a PM to you )??

**Comment by CpuDbg** [comment]
jmp[at]ollydbg.com

> > > Thanks for the clarification, maybe you find time/interest to read and answer some reverser questions about CpuDbg in next topic: https://forum.exetools.com/showthread.php?t=21003
> > > Some people also warned about the presence of suspicios references to video card names/references, as many malicious software contains. With a few clarifications the doubts are resolved.
> > > Thanks you for your effort in advance.
> > 
> > 
> > I'm sorry, I don't have an account for that forum, and I can't register because it requires an invitation code :(
> 
> Hi How can I reach you ( send a PM to you )??

e-mail: jmp[at]ollydbg.com
