### ISSUE TITLE
English localization

### ISSUE THREAD

**Issue by greenozon** [CpuDbg/CpuDbg#3]
If you select English, you still have majority non-translated strings, eg:

![image](https://github.com/CpuDbg/CpuDbg/assets/765343/e215e328-c400-49f7-bc5b-61889352df28)

**Comment by CpuDbg** [comment]
![image](https://github.com/CpuDbg/CpuDbg/assets/134661959/ec7e8f87-97d5-4238-91a5-8adcac462095)

Because I used the MBCS character set in the CpuDbg project, there is a possibility that it may display garbled characters on certain systems. In the upcoming versions, I will change it to UNICODE. You can try again when that update is available.

Translation: Since I used the MBCS character set in the CpuDbg project, there is a chance of displaying garbled characters on some systems. In future versions, I will switch to UNICODE. You can give it another try then.

**Comment by greenozon** [comment]
There are some langauge files over here: "CpuDbg v0.7.2\Config\Language\Language_en.xml" 
but looks like debugger itself needs to add more localization items to cover 100%?

**Comment by CpuDbg** [comment]
> There are some langauge files over here: "CpuDbg v0.7.2\Config\Language\Language_en.xml" but looks like debugger itself needs to add more localization items to cover 100%?

Currently, language support is limited to Chinese and English. Other languages either have no content available or have incomplete translations.

**Comment by CpuDbg** [comment]
The mbcs problem has been fixed in cpudbg v0.7.5 release.
